### ISSUE TITLE
Error to run quickstart using Gitter Template

### ISSUE THREAD

**Issue by geazi-anc** [http4s/http4s.g8#335]
I found an error to run gitter template for HTTP4S (0.23-scala3 version).
See steps below, such as java, scala and sbt version:

$ sbt new http4s/http4s.g8 --branch 0.23-scala3
name [quickstart]:
organization [com.example]:
package [com.example.quickstart]:

Template applied in /home/geazi/repos/mytest/./quickstart
$ cd quickstart
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
$ scala --version
Scala code runner version 3.3.0 -- Copyright 2002-2023, LAMP/EPFL
$ sbt --version
sbt version in this project: 1.9.3
sbt script version: 1.9.1
$ sbt run
[info] welcome to sbt 1.9.3 (AdoptOpenJDK Java 1.8.0_292)
[info] loading settings for project quickstart-build from plugins.sbt ...
[info] loading project definition from /home/geazi/repos/mytest/quickstart/project
[info] loading settings for project root from build.sbt ...
[info] set current project to quickstart (in build file:/home/geazi/repos/mytest/quickstart/)
[info] compiling 5 Scala sources to /home/geazi/repos/mytest/quickstart/target/scala-3.3.0/classes ...
[info] running com.example.quickstart.Main 
^[[ZException in thread "sbt-bg-threads-1" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:103)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.slf4j.LoggerFactory.safelyInstantiate(LoggerFactory.java:134)
        at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:115)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:178)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
        at org.typelevel.log4cats.slf4j.Slf4jLogger$.getLoggerFromName(Slf4jLogger.scala:30)
        at org.typelevel.log4cats.slf4j.Slf4jLogger$.getLogger(Slf4jLogger.scala:27)
        at org.http4s.ember.client.EmberClientBuilderCompanionPlatform.defaultLogger(EmberClientBuilderCompanionPlatform.scala:33)
        at org.http4s.ember.client.EmberClientBuilderCompanionPlatform.defaultLogger$(EmberClientBuilderCompanionPlatform.scala:31)
        at org.http4s.ember.client.EmberClientBuilder$.defaultLogger(EmberClientBuilder.scala:390)
        at org.http4s.ember.client.EmberClientBuilder$.default(EmberClientBuilder.scala:399)
        at com.example.quickstart.QuickstartServer$.run(QuickstartServer.scala:16)
        at com.example.quickstart.Main$.<clinit>(Main.scala:6)
        at com.example.quickstart.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.Run.invokeMain(Run.scala:144)
        at sbt.Run.execute$1(Run.scala:94)
        at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
        at sbt.Run$.executeSuccess(Run.scala:187)
        at sbt.Run.runWithLoader(Run.scala:121)
        at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1986)
        at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1925)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:367)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[success] Total time: 16 s, completed Aug 15, 2023 3:14:43 PM

**Comment by froth** [comment]
Hi, thanks for the report and the complete information!

I believe the problem is that the logback version we bundle does not support Java 8 any longer (https://logback.qos.ch/dependencies.html).

Could you try if downgrading logback-classic in the build.sbt to `1.3.11`. Does this fix the error?

If this is so there are two questions for us I think:
- should we use the 1.3 line of logback for this template to allow for continuous Java 8 support? If not: Where should we document that it simply does not work with java Versions below 11?
- how can we improve our testing, as we build this template with Java 8 and it does not throw errors in the pipeline as (I think) it does not get started.

**Comment by froth** [comment]
I can confirm that the template does not work with java 8. I will open a pr downgrading logback-classic.

**Comment by geazi-anc** [comment]
> Hi, thanks for the report and the complete information!
> 
> I believe the problem is that the logback version we bundle does not support Java 8 any longer (https://logback.qos.ch/dependencies.html).
> 
> Could you try if downgrading logback-classic in the build.sbt to `1.3.11`. Does this fix the error?
> 
> If this is so there are two questions for us I think:
> 
> * should we use the 1.3 line of logback for this template to allow for continuous Java 8 support? If not: Where should we document that it simply does not work with java Versions below 11?
> * how can we improve our testing, as we build this template with Java 8 and it does not throw errors in the pipeline as (I think) it does not get started.

Yeah, it solved my problem, thank you!
* Please, document in quickstart session of HTTP4S website that template not works with java less than 11.
* Yes, it would be interesting add a test to fail if there are error compilations because of version incompatibility.

Thank you again for!
